version: '3.4'
services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/vscode:delegated
      # For building dependencies always use a volume, you get waaaay better performance.
      - target:/vscode/target
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    working_dir: /vscode
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/newsletter
      - APP_ENVIRONMENT=local
  postgres:
    image: circleci/postgres:13.5-bullseye-ram
    shm_size: 256m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
      - TZ="Asia/Tokyo"
    ports:
      - "5432:5432"
volumes:
  # The volume for cargo build
  target: