---
database:
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application:
  port: 8000
  base_url: "http://127.0.0.1"
  hmac_secret: "51b81abeef5fca409e020e73ea855c5d68bad6db87e94e042b5719987a42c10e"
email_client:
  base_url: "localhost"
  sender_email: "sender@example.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000